# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0002_article_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='snippet',
            field=models.TextField(),
        ),
    ]
